---
camera:
  width: 640
  height: 480
  fps: 30
  exposure: 10000.0
  gain: 10.0

preprocess:
  gaussian_k_size: 3      # 高斯模糊核大小
  gaussian_sigma: 1.3     # 高斯模糊sigma
  rdc_exposure_x: 0.30    # 降曝光参数1   <1,对比度增加；  >1,对比度降低，变灰，模糊
  rdc_exposure_y: -60.0   # 降曝光参数2   >0, 变亮；      <0, 变暗
  min_area: 30.0          # 灯条最小面积
  max_area: 50.0          # 灯条最大面积
  min_ratio: 2.0          # 灯条最小宽高比
  max_ratio: 4.0          # 灯条最大宽高比
  max_angle: 25.0         # 灯条最大偏转角

armor:
  max_height_diff: 3.0    # 灯条最大高度差
  min_dist_ratio: 1.2     # 最小距离比
  max_dist_ratio: 4.5     # 最大距离比
  max_angle_diff: 30.0    # 最大角度差
  w_h_ratio: 12.3          # 装甲板宽高比

ballistic:
  bullet_speed: 28.0      # 弹速
  gravity: 9.8            # 重力加速度
  camera_offset_x: 0      # 偏移X
  camera_offset_y: -50    # 偏移Y
  camera_offset_z: 100    # 偏移Z

kalman:
  processNoisePos: 0.0001      # 位置过程噪声
  processNoiseVel: 0.01         # 速度过程噪声
  measurementNoisePos: 0.01     # 观测噪声
  initialErrorCov: 1.0          # 初始误差协方差
  angularVelocity: 7.33         # 水平转速 (rad/s)

serial:
  port: "/dev/tyUSB0"     # 串口名
  baud: 115200            # 波特率